### ISSUE TITLE
Configuration file format is newer than the current version issue is still present in 1.96.0

### ISSUE THREAD

**Issue by ora** [splunk/splunk-connect-for-syslog#1298]
[2021-10-14T12:49:13.566626] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.32) in the @version directive. syslog-ng will operate at its highest supported version in this mode; config-version='3.33'

**Comment by rfaircloth-splunk** [comment]
please confirm resolved now

**Comment by ora** [comment]
Still present for me in 1.98.0

Oct 22 01:50:28 BOX entrypoint.sh[8377]: sc4s version=1.98.0
Oct 22 01:50:29 BOX entrypoint.sh[8377]: starting goss
Oct 22 01:50:29 BOX entrypoint.sh[8377]: [2021-10-22T01:50:29.234766] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.32) in the @version directive. syslog-ng will operate at its highest supported version in this mode; config-version='3.33'
Oct 22 01:50:30 BOX entrypoint.sh[8377]: starting syslog-ng
Oct 22 01:50:30 BOX entrypoint.sh[8377]: [2021-10-22T01:50:30.337495] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.32) in the @version directive. syslog-ng will operate at its highest supported version in this mode; config-version='3.33'
