### ISSUE TITLE
Azure ACI refusing to download 2.47 image

### ISSUE THREAD

**Issue by lachlanhorsey** [splunk/splunk-connect-for-syslog#2022]
Hi team,

This issue has already been raised directly with Splunk in #3176185, however raising here too...

Version 2.47 release to the Github repo did not include the relevant Docker manifest files that Azure requires for security reasons. This caused a large outage for one of our clients. 

Has this issue been rectified in v2.48? What has been put in place to ensure this does not happen again?

Please see below from Microsoft Engineer:
------------------------------
As per our discussion and screen sharing you were able to pull the image ‘ghcr.io/splunk/splunk-connect-for-syslog/container2:2’ on your local .

* However, you are getting the Imagenotaccessible error for the same image when you are trying to create an ACI.
* ACI by design do not pull images which do not have the manifest file for the security reasons.
* Docker manifests describe the layers inside an image. A manifest enables exact comparison of two images, even if they have different tags assigned. Manifests are expressed in JSON and contain information about the image’s layers and architectures.
-------------------

Cheers,
Lachlan

**Comment by bparmar-splunk** [comment]
@lachlanhorsey,
We have released new version [2.48.2](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v2.48.2).
Please validate your usecase and reach out in case of any queries.

Thank you.

**Comment by lachlanhorsey** [comment]
@bparmar-splunk thank you, I have validated v2.48.2 fixes the ACI errors. However, :2 tag is still not applied to this fixed version, so following the https://splunk.github.io/splunk-connect-for-syslog/main/upgrade/ best practice of pulling container2:2 still causes issues. Will you update the tagging in the repository?

Cheers!

**Comment by bparmar-splunk** [comment]
@lachlanhorsey,
When any new version is released, several tags are updated with new image. `:2` is part of them.
And it gets pointed to new image automatically hence we are not updating the tags manually.
Currently if you fetch the image using `:2` tag, it will download latest image.

**Comment by lachlanhorsey** [comment]
Thank you @bparmar-splunk, I've got my end to retest and you're correct, :2 is pulling the correct version. Sorry for the confusion. Do we now have confidence that the required manifest file will be included in all future releases?

If so, happy for this issue to be closed.

**Comment by bparmar-splunk** [comment]
Yes. Going ahead we will have this setting applied for all future releases.
Thank you.

**Comment by lachlanhorsey** [comment]
Thank you, appreciate you looking into this.
